# frozen_string_literal: true

module RailsAiContext
  module Serializers
    # Generates CLAUDE.md optimized for Claude Code.
    # In :compact mode (default), produces ≤150 lines with MCP tool references.
    # In :full mode, delegates to MarkdownSerializer with behavioral rules.
    class ClaudeSerializer
      attr_reader :context

      def initialize(context)
        @context = context
      end

      def call
        if RailsAiContext.configuration.context_mode == :full
          FullClaudeSerializer.new(context).call
        else
          render_compact
        end
      end

      private

      def render_compact
        lines = []
        lines.concat(render_header)
        lines.concat(render_stack_overview)
        lines.concat(render_key_models)
        lines.concat(render_notable_gems)
        lines.concat(render_architecture)
        lines.concat(render_ui_patterns)
        lines.concat(render_mcp_guide)
        lines.concat(render_conventions)
        lines.concat(render_commands)
        lines.concat(render_footer)

        # Enforce max lines
        max = RailsAiContext.configuration.claude_max_lines
        if lines.size > max
          lines = lines.first(max - 2)
          lines << ""
          lines << "_Context trimmed. Use MCP tools for full details._"
        end

        lines.join("\n")
      end

      def render_header
        [
          "# #{context[:app_name]} — AI Context",
          "",
          "> Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}",
          "> Generated by rails-ai-context v#{RailsAiContext::VERSION}",
          ""
        ]
      end

      def render_stack_overview
        lines = [ "## Stack" ]

        schema = context[:schema]
        if schema && !schema[:error]
          lines << "- Database: #{schema[:adapter]} — #{schema[:total_tables]} tables"
        end

        models = context[:models]
        if models.is_a?(Hash) && !models[:error]
          lines << "- Models: #{models.size}"
        end

        routes = context[:routes]
        if routes && !routes[:error]
          ctrl_count = (routes[:by_controller] || {}).keys.size
          lines << "- Routes: #{routes[:total_routes]} across #{ctrl_count} controllers"
        end

        auth = context[:auth]
        if auth.is_a?(Hash) && !auth[:error]
          parts = []
          parts << "Devise" if auth.dig(:authentication, :devise)&.any?
          parts << "Rails 8 auth" if auth.dig(:authentication, :rails_auth)
          parts << "Pundit" if auth.dig(:authorization, :pundit)&.any?
          parts << "CanCanCan" if auth.dig(:authorization, :cancancan)
          lines << "- Auth: #{parts.join(' + ')}" if parts.any?
        end

        jobs = context[:jobs]
        if jobs.is_a?(Hash) && !jobs[:error]
          job_count = jobs[:jobs]&.size || 0
          mailer_count = jobs[:mailers]&.size || 0
          channel_count = jobs[:channels]&.size || 0
          parts = []
          parts << "#{job_count} jobs" if job_count > 0
          parts << "#{mailer_count} mailers" if mailer_count > 0
          parts << "#{channel_count} channels" if channel_count > 0
          lines << "- Async: #{parts.join(', ')}" if parts.any?
        end

        migrations = context[:migrations]
        if migrations.is_a?(Hash) && !migrations[:error]
          pending = migrations[:pending]
          lines << "- Migrations: #{migrations[:total]} total, #{pending&.size || 0} pending"
        end

        lines << ""
        lines
      end

      def render_key_models
        models = context[:models]
        return [] unless models.is_a?(Hash) && !models[:error] && models.any?

        max_show = 15
        lines = [ "## Key models (#{models.size} total)" ]
        models.keys.sort.first(max_show).each do |name|
          data = models[name]
          assoc_count = (data[:associations] || []).size
          val_count = (data[:validations] || []).size
          top_assocs = (data[:associations] || []).first(3).map { |a| "#{a[:type]} :#{a[:name]}" }.join(", ")
          line = "- **#{name}**"
          line += " (#{assoc_count}a, #{val_count}v)" if assoc_count > 0 || val_count > 0
          line += " — #{top_assocs}" if top_assocs && !top_assocs.empty?
          lines << line
          scopes = (data[:scopes] || [])
          constants = (data[:constants] || [])
          if scopes.any? || constants.any?
            extras = []
            extras << "scopes: #{scopes.join(', ')}" if scopes.any?
            constants.each { |c| extras << "#{c[:name]}: #{c[:values].join(', ')}" }
            lines << "  #{extras.join(' | ')}"
          end
        end
        lines << "- _...#{models.size - max_show} more (use `rails_get_model_details` tool)_" if models.size > max_show
        lines << ""
        lines
      end

      def render_notable_gems
        gems = context[:gems]
        return [] unless gems.is_a?(Hash) && !gems[:error]
        notable = gems[:notable_gems] || gems[:notable] || gems[:detected] || []
        return [] if notable.empty?

        lines = [ "## Gems" ]
        grouped = notable.group_by { |g| g[:category]&.to_s || "other" }
        grouped.each do |category, gem_list|
          names = gem_list.map { |g| g[:name] }.join(", ")
          lines << "- **#{category}**: #{names}"
        end
        lines << ""
        lines
      end

      def render_architecture
        conv = context[:conventions]
        return [] unless conv.is_a?(Hash) && !conv[:error]

        arch = conv[:architecture] || []
        patterns = conv[:patterns] || []
        return [] if arch.empty? && patterns.empty?

        lines = [ "## Architecture" ]
        arch.each { |p| lines << "- #{p}" }
        patterns.first(8).each { |p| lines << "- #{p}" }

        # List service objects and jobs from conventions directory_structure
        dir_struct = conv[:directory_structure] || {}

        if dir_struct["app/services"]
          begin
            root = defined?(Rails) ? Rails.root.to_s : Dir.pwd
            service_files = Dir.glob(File.join(root, "app", "services", "*.rb"))
              .map { |f| File.basename(f, ".rb").camelize }
              .reject { |s| s == "ApplicationService" }
            lines << "" << "**Services:** #{service_files.join(', ')}" if service_files.any?
          rescue; end
        end

        if dir_struct["app/jobs"]
          begin
            root = defined?(Rails) ? Rails.root.to_s : Dir.pwd
            job_files = Dir.glob(File.join(root, "app", "jobs", "*.rb"))
              .map { |f| File.basename(f, ".rb").camelize }
              .reject { |j| j == "ApplicationJob" }
            lines << "**Jobs:** #{job_files.join(', ')}" if job_files.any?
          rescue; end
        end

        lines << ""
        lines
      end

      def render_ui_patterns
        vt = context[:view_templates]
        return [] unless vt.is_a?(Hash) && !vt[:error]
        patterns = vt[:ui_patterns] || {}
        components = patterns[:components] || []
        return [] if components.empty?

        lines = [ "## UI Patterns" ]

        # Color scheme summary
        scheme = patterns[:color_scheme] || {}
        if scheme.any?
          parts = []
          parts << "Primary: #{scheme[:primary]}" if scheme[:primary]
          parts << "Text: #{scheme[:text]}" if scheme[:text]
          lines << parts.join(" | ") if parts.any?
        end

        lines << ""
        components.first(15).each do |comp|
          lines << "- #{comp[:label]}: `#{comp[:classes]}`"
        end

        # Form layout
        fl = patterns[:form_layout] || {}
        if fl.any?
          lines << "" << "Form: #{fl.values.join(', ')}"
        end
        lines << ""
        lines
      end

      def render_mcp_guide # rubocop:disable Metrics/MethodLength
        [
          "## MCP Tools (13) — ALWAYS Use These First",
          "",
          "Use MCP for reference files (schema, routes, tests). Read directly if you'll edit.",
          "MCP tools return line numbers. Start with `detail:\"summary\"`.",
          "",
          "- `rails_get_schema(detail:\"summary\")` → `rails_get_schema(table:\"name\")`",
          "- `rails_get_model_details(detail:\"summary\")` → `rails_get_model_details(model:\"Name\")`",
          "- `rails_get_routes(detail:\"summary\")` → `rails_get_routes(controller:\"name\")`",
          "- `rails_get_controllers(controller:\"Name\", action:\"index\")` — one action's source code",
          "- `rails_get_view(controller:\"cooks\")` — view list; `(path:\"cooks/index.html.erb\")` — content",
          "- `rails_get_stimulus(detail:\"summary\")` → `(controller:\"name\")` — targets, actions, values",
          "- `rails_get_test_info(detail:\"full\")` — fixtures, factories, helpers; `(model:\"Cook\")` — tests",
          "- `rails_get_config` | `rails_get_gems` | `rails_get_conventions` | `rails_search_code`",
          "- `rails_validate(files:[\"path/to/file.rb\"])` — validate Ruby, ERB, JS syntax in one call",
          ""
        ]
      end

      def render_conventions
        conv = context[:conventions]
        return [] unless conv.is_a?(Hash) && !conv[:error]

        config_files = conv[:config_files] || []
        return [] if config_files.empty?

        lines = [ "## Key config files" ]
        config_files.first(5).each { |f| lines << "- `#{f}`" }
        lines << ""
        lines
      end

      def test_command
        context.dig(:tests, :framework) == "rspec" ? "bundle exec rspec" : "rails test"
      end

      def render_commands
        [
          "## Commands",
          "- `bin/dev` — start dev server",
          "- `#{test_command}` — run tests",
          "- `rails db:migrate` — run pending migrations",
          ""
        ]
      end

      def render_footer
        [
          "## Rules",
          "- Follow existing patterns and conventions",
          "- Use the MCP tools to check schema before writing migrations",
          "- Match existing code style",
          "- Run tests after changes",
          "- After editing, ALWAYS use `rails_validate(files:[...])` — do NOT use separate ruby -c / erb / node -c calls",
          "- Do NOT re-read files to verify edits — trust your Edit, validate syntax only",
          "- Stimulus controllers auto-register — no manual import in controllers/index.js needed",
          ""
        ]
      end
    end

    # Internal: full-mode Claude serializer (wraps MarkdownSerializer with behavioral rules)
    class FullClaudeSerializer < MarkdownSerializer
      private

      def header
        <<~MD
          # #{context[:app_name]} — AI Context

          > Auto-generated by rails-ai-context v#{RailsAiContext::VERSION}
          > Generated: #{context[:generated_at]}
          > Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}

          This file gives Claude Code deep context about this Rails application's
          structure, patterns, and conventions. Use it to write idiomatic code
          that matches this project's style.
        MD
      end

      def footer
        rules = []
        rules << "## Behavioral Rules"
        rules << ""
        rules << "When working in this codebase:"
        rules << "- Follow existing patterns and conventions detected above"
        rules << "- Use the database schema as the source of truth for column names and types"
        rules << "- Respect existing associations and validations when modifying models"
        rules << "- Match the project's architecture style (#{architecture_summary})" if architecture_summary
        rules << "- Run `#{test_command}` after making changes to verify correctness"
        rules << ""
        rules << super
        rules.join("\n")
      end

      def architecture_summary
        arch = context.dig(:conventions, :architecture)
        arch&.any? ? arch.join(", ") : nil
      end

      def test_command
        context.dig(:tests, :framework) == "rspec" ? "bundle exec rspec" : "rails test"
      end
    end
  end
end
