# frozen_string_literal: true

module RailsAiContext
  module Serializers
    # Generates GitHub Copilot instructions.
    # In :compact mode (default), produces ≤500 lines with MCP tool references.
    # In :full mode, delegates to MarkdownSerializer with Copilot header.
    class CopilotSerializer
      include TestCommandDetection
      include StackOverviewHelper
      include DesignSystemHelper
      include ToolGuideHelper

      attr_reader :context

      def initialize(context)
        @context = context
      end

      def call
        if RailsAiContext.configuration.context_mode == :full
          FullCopilotSerializer.new(context).call
        else
          render_compact
        end
      end

      private

      def render_compact
        lines = []
        lines << "# #{context[:app_name]} — Copilot Context"
        lines << ""
        lines << "Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}"
        lines << ""

        # Stack overview
        lines << "## Stack"
        schema = context[:schema]
        lines << "- Database: #{schema[:adapter]} — #{schema[:total_tables]} tables" if schema && !schema[:error]

        models = context[:models]
        lines << "- Models: #{models.size}" if models.is_a?(Hash) && !models[:error]

        routes = context[:routes]
        if routes && !routes[:error]
          lines << "- Routes: #{routes[:total_routes]} across #{(routes[:by_controller] || {}).size} controllers"
        end

        lines.concat(full_preset_stack_lines)

        # Gems by category
        gems = context[:gems]
        if gems.is_a?(Hash) && !gems[:error]
          notable = gems[:notable_gems] || gems[:notable] || gems[:detected] || []
          notable.group_by { |g| g[:category]&.to_s || "other" }.each do |cat, list|
            lines << "- #{cat}: #{list.map { |g| g[:name] }.join(', ')}"
          end
        end

        lines << ""

        # Models — Copilot gets more detail (up to 25 with associations)
        if models.is_a?(Hash) && !models[:error] && models.any?
          lines << "## Models (#{models.size})"
          models.keys.sort.first(25).each do |name|
            data = models[name]
            assocs = (data[:associations] || []).map { |a| "#{a[:type]} :#{a[:name]}" }.join(", ")
            line = "- **#{name}**"
            line += " — #{assocs}" unless assocs.empty?
            lines << line
          end
          lines << "- _...#{models.size - 25} more_" if models.size > 25
          lines << ""
        end

        # Architecture
        conv = context[:conventions]
        if conv.is_a?(Hash) && !conv[:error]
          arch = conv[:architecture] || []
          patterns = conv[:patterns] || []
          if arch.any? || patterns.any?
            arch_labels = RailsAiContext::Tools::GetConventions::ARCH_LABELS rescue {}
            pattern_labels = RailsAiContext::Tools::GetConventions::PATTERN_LABELS rescue {}
            lines << "## Architecture"
            arch.each { |p| lines << "- #{arch_labels[p] || p}" }
            patterns.first(10).each { |p| lines << "- #{pattern_labels[p] || p}" }
            lines << ""
          end
        end

        # Design System
        lines.concat(render_design_system(context, max_lines: 35))

        # Tools reference (respects tool_mode)
        lines.concat(render_tools_guide)

        # Conventions
        lines << "## Conventions"
        lines << "- Follow existing patterns and naming conventions"
        lines << "- Use the introspection tools to check schema before writing migrations"
        lines << "- Run `#{detect_test_command}` after changes"
        lines << ""

        lines.join("\n")
      end
    end

    # Internal: full-mode Copilot serializer (wraps MarkdownSerializer)
    class FullCopilotSerializer < MarkdownSerializer
      private

      def header
        <<~MD
          # #{context[:app_name]} — Copilot Instructions

          > Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}
          > Auto-generated by rails-ai-context v#{RailsAiContext::VERSION}

          Use this context to generate code that fits this project's structure and patterns.
        MD
      end

      def footer
        <<~MD
          ---
          _Auto-generated. Run `rails ai:context` to regenerate._
        MD
      end
    end
  end
end
