# frozen_string_literal: true

module RailsAiContext
  module Serializers
    # Generates AI-friendly markdown context files from introspection data.
    # Outputs: CLAUDE.md (for Claude Code), .windsurfrules, etc.
    class MarkdownSerializer # rubocop:disable Metrics/ClassLength
      attr_reader :context

      def initialize(context)
        @context = context
      end

      # @return [String] full markdown document
      def call
        sections = []
        sections << header
        sections << app_overview
        sections << schema_section if context[:schema]
        sections << models_section if context[:models]
        sections << routes_section if context[:routes]
        sections << jobs_section if context[:jobs]
        sections << gems_section if context[:gems]
        sections << conventions_section if context[:conventions]
        sections << controllers_section if context[:controllers]
        sections << views_section if context[:views]
        sections << turbo_section if context[:turbo]
        sections << active_storage_section if context[:active_storage]
        sections << action_text_section if context[:action_text]
        sections << i18n_section if context[:i18n]
        sections << config_section if context[:config]
        sections << assets_section if context[:assets]
        sections << auth_section if context[:auth]
        sections << api_section if context[:api]
        sections << tests_section if context[:tests]
        sections << rake_tasks_section if context[:rake_tasks]
        sections << devops_section if context[:devops]
        sections << action_mailbox_section if context[:action_mailbox]
        sections << migrations_section if context[:migrations]
        sections << seeds_section if context[:seeds]
        sections << middleware_section if context[:middleware]
        sections << engines_section if context[:engines]
        sections << multi_database_section if context[:multi_database]
        sections << footer
        sections.compact.join("\n\n")
      end

      private

      def header
        <<~MD
          # #{context[:app_name]} — AI Context

          > Auto-generated by rails-ai-context v#{RailsAiContext::VERSION}
          > Generated: #{context[:generated_at]}
          > Rails #{context[:rails_version]} | Ruby #{context[:ruby_version]}

          This file gives AI assistants (Claude Code, Cursor, Copilot) deep context
          about this Rails application's structure, patterns, and conventions.
        MD
      end

      def app_overview
        conv = context[:conventions] || {}
        arch = conv[:architecture] || []
        patterns = conv[:patterns] || []

        lines = [ "## Overview" ]
        lines << "- **Architecture:** #{arch.join(', ')}" if arch.any?
        lines << "- **Patterns:** #{patterns.join(', ')}" if patterns.any?
        lines.join("\n")
      end

      def schema_section
        schema = context[:schema]
        return if schema[:error]

        lines = [ "## Database Schema (#{schema[:total_tables]} tables)" ]
        schema[:tables]&.each do |name, data|
          cols = (data[:columns] || []).map { |c| "`#{c[:name]}` (#{c[:type]})" }.join(", ")
          lines << "### #{name}"
          lines << cols
        end
        lines.join("\n\n")
      end

      def models_section
        models = context[:models]
        return if models.is_a?(Hash) && models[:error]

        lines = [ "## Models (#{models.size})" ]
        models.each do |name, data|
          next if data[:error]
          assocs = (data[:associations] || []).map { |a| "#{a[:type]} :#{a[:name]}" }.join(", ")
          lines << "### #{name}"
          lines << "- Table: `#{data[:table_name]}`" if data[:table_name]
          lines << "- Associations: #{assocs}" if assocs.present?
          if data[:validations]&.any?
            vals = data[:validations].map { |v| "#{v[:kind]} on #{v[:attributes].join(', ')}" }.join("; ")
            lines << "- Validations: #{vals}"
          end
          lines << "- Enums: #{data[:enums].keys.join(', ')}" if data[:enums]&.any?
        end
        lines.join("\n")
      end

      def routes_section
        routes = context[:routes]
        return if routes[:error]

        lines = [ "## Routes (#{routes[:total_routes]} total)" ]
        routes[:by_controller]&.sort&.each do |ctrl, actions|
          lines << "### #{ctrl}"
          actions.each do |r|
            lines << "- `#{r[:verb]} #{r[:path]}` → #{r[:action]}"
          end
        end
        lines.join("\n")
      end

      def jobs_section
        jobs = context[:jobs]
        parts = []

        if jobs[:jobs]&.any?
          parts << "## Background Jobs"
          jobs[:jobs].each { |j| parts << "- `#{j[:name]}` (queue: #{j[:queue]})" }
        end

        if jobs[:mailers]&.any?
          parts << "## Mailers"
          jobs[:mailers].each { |m| parts << "- `#{m[:name]}`: #{m[:actions].join(', ')}" }
        end

        if jobs[:channels]&.any?
          parts << "## Action Cable Channels"
          jobs[:channels].each { |c| parts << "- `#{c[:name]}`" }
        end

        parts.join("\n") if parts.any?
      end

      def gems_section
        gems = context[:gems]
        return if gems[:error]

        notable = gems[:notable_gems] || []
        return if notable.empty?

        lines = [ "## Notable Gems" ]
        notable.group_by { |g| g[:category] }.sort.each do |cat, group|
          lines << "### #{cat.capitalize}"
          group.each { |g| lines << "- **#{g[:name]}** (#{g[:version]}): #{g[:note]}" }
        end
        lines.join("\n")
      end

      def conventions_section
        conv = context[:conventions]
        return unless conv[:directory_structure]&.any?

        lines = [ "## Project Structure" ]
        conv[:directory_structure].sort.each do |dir, count|
          lines << "- `#{dir}/` — #{count} files"
        end
        lines.join("\n")
      end

      def controllers_section
        data = context[:controllers]
        return if data[:error]

        controllers = data[:controllers] || {}
        return if controllers.empty?

        lines = [ "## Controllers (#{controllers.size})" ]
        controllers.each do |name, info|
          next if info[:error]
          lines << "### #{name}"
          lines << "- Parent: `#{info[:parent_class]}`" if info[:parent_class]
          lines << "- API controller: yes" if info[:api_controller]
          lines << "- Actions: #{info[:actions]&.join(', ')}" if info[:actions]&.any?
          if info[:filters]&.any?
            lines << "- Filters: #{info[:filters].map { |f| "#{f[:kind]} #{f[:name]}" }.join(', ')}"
          end
          lines << "- Strong params: #{info[:strong_params].join(', ')}" if info[:strong_params]&.any?
        end
        lines.join("\n")
      end

      def views_section
        data = context[:views]
        return if data[:error]

        lines = [ "## Views" ]
        lines << "- Layouts: #{data[:layouts].join(', ')}" if data[:layouts]&.any?
        lines << "- Template engines: #{data[:template_engines].join(', ')}" if data[:template_engines]&.any?

        if data[:templates]&.any?
          lines << "### Templates by controller"
          data[:templates].each do |ctrl, templates|
            lines << "- `#{ctrl}/`: #{templates.join(', ')}"
          end
        end

        if data[:helpers]&.any?
          lines << "### Helpers"
          data[:helpers].each { |h| lines << "- `#{h[:file]}`: #{h[:methods].join(', ')}" }
        end

        lines << "- View components: #{data[:view_components].size}" if data[:view_components]&.any?
        lines.join("\n")
      end

      def turbo_section
        data = context[:turbo]
        return if data[:error]
        return if data[:turbo_frames]&.empty? && data[:turbo_streams]&.empty? && data[:model_broadcasts]&.empty?

        lines = [ "## Hotwire / Turbo" ]
        if data[:turbo_frames]&.any?
          lines << "### Turbo Frames"
          data[:turbo_frames].each { |f| lines << "- `#{f[:id]}` in #{f[:file]}" }
        end
        if data[:turbo_streams]&.any?
          lines << "### Turbo Stream Templates"
          data[:turbo_streams].each { |t| lines << "- `#{t}`" }
        end
        if data[:model_broadcasts]&.any?
          lines << "### Model Broadcasts"
          data[:model_broadcasts].each { |b| lines << "- `#{b[:model]}`: #{b[:methods].join(', ')}" }
        end
        lines.join("\n")
      end

      def active_storage_section
        data = context[:active_storage]
        return if data[:error]
        return unless data[:attachments]&.any?

        lines = [ "## Active Storage" ]
        data[:attachments].each { |a| lines << "- `#{a[:model]}` #{a[:type]} :#{a[:name]}" }
        lines << "- Storage services: #{data[:storage_services].join(', ')}" if data[:storage_services]&.any?
        lines.join("\n")
      end

      def action_text_section
        data = context[:action_text]
        return if data[:error]
        return unless data[:rich_text_fields]&.any?

        lines = [ "## Action Text" ]
        data[:rich_text_fields].each { |f| lines << "- `#{f[:model]}` has_rich_text :#{f[:field]}" }
        lines.join("\n")
      end

      def i18n_section
        data = context[:i18n]
        return if data[:error]

        lines = [ "## Internationalization" ]
        lines << "- Default locale: #{data[:default_locale]}"
        lines << "- Available locales: #{data[:available_locales]&.join(', ')}"
        lines << "- Locale files: #{data[:total_locale_files]}" if data[:total_locale_files]&.positive?
        lines.join("\n")
      end

      def config_section
        data = context[:config]
        return if data[:error]

        lines = [ "## Configuration" ]
        lines << "- Cache store: #{data[:cache_store]}" if data[:cache_store]
        lines << "- Session store: #{data[:session_store]}" if data[:session_store]
        lines << "- Timezone: #{data[:timezone]}" if data[:timezone].present?
        if data[:initializers]&.any?
          lines << "- Initializers: #{data[:initializers].join(', ')}"
        end
        lines.join("\n")
      end

      def assets_section
        data = context[:assets]
        return if data[:error]

        lines = [ "## Asset Pipeline" ]
        lines << "- Pipeline: #{data[:pipeline]}" if data[:pipeline]
        lines << "- JS bundler: #{data[:js_bundler]}" if data[:js_bundler]
        lines << "- CSS framework: #{data[:css_framework]}" if data[:css_framework]
        if data[:importmap_pins]&.any?
          lines << "- Importmap pins: #{data[:importmap_pins].join(', ')}"
        end
        lines.join("\n")
      end

      def auth_section
        data = context[:auth]
        return if data[:error]

        authn = data[:authentication] || {}
        authz = data[:authorization] || {}
        return if authn.empty? && authz.empty?

        lines = [ "## Authentication & Authorization" ]
        if authn[:devise]
          lines << "### Devise"
          authn[:devise].each { |d| lines << "- `#{d[:model]}`: #{d[:matches].join(', ')}" }
        end
        lines << "- Rails 8 built-in auth detected" if authn[:rails_auth]
        lines << "- has_secure_password: #{authn[:has_secure_password].join(', ')}" if authn[:has_secure_password]
        if authz[:pundit]
          lines << "### Pundit Policies"
          authz[:pundit].each { |p| lines << "- `#{p}`" }
        end
        lines << "- CanCanCan: Ability class detected" if authz[:cancancan]
        lines.join("\n")
      end

      def api_section
        data = context[:api]
        return if data[:error]

        lines = [ "## API Layer" ]
        lines << "- API-only mode: #{data[:api_only]}"
        if data[:api_versioning]&.any?
          lines << "- API versions: #{data[:api_versioning].join(', ')}"
        end
        if data[:serializers]&.any?
          lines << "- Jbuilder templates: #{data[:serializers][:jbuilder]}" if data[:serializers][:jbuilder]
          if data[:serializers][:serializer_classes]&.any?
            lines << "- Serializers: #{data[:serializers][:serializer_classes].join(', ')}"
          end
        end
        if data[:graphql]
          lines << "### GraphQL"
          lines << "- Types: #{data[:graphql][:types]}, Mutations: #{data[:graphql][:mutations]}"
        end
        lines.join("\n")
      end

      def tests_section
        data = context[:tests]
        return if data[:error]

        lines = [ "## Testing" ]
        lines << "- Framework: #{data[:framework]}"
        lines << "- Factories: #{data[:factories][:location]} (#{data[:factories][:count]} files)" if data[:factories]
        lines << "- Fixtures: #{data[:fixtures][:location]} (#{data[:fixtures][:count]} files)" if data[:fixtures]
        lines << "- System tests: #{data[:system_tests][:location]}" if data[:system_tests]
        lines << "- CI: #{data[:ci_config].join(', ')}" if data[:ci_config]&.any?
        lines << "- Coverage: #{data[:coverage]}" if data[:coverage]
        lines.join("\n")
      end

      def rake_tasks_section
        data = context[:rake_tasks]
        return if data[:error]
        return unless data[:tasks]&.any?

        lines = [ "## Rake Tasks" ]
        data[:tasks].each do |task|
          desc = task[:description] ? " — #{task[:description]}" : ""
          lines << "- `#{task[:name]}`#{desc}"
        end
        lines.join("\n")
      end

      def devops_section
        data = context[:devops]
        return if data[:error]

        lines = [ "## DevOps" ]
        if data[:puma]
          lines << "### Puma"
          lines << "- Threads: #{data[:puma][:threads_min]}-#{data[:puma][:threads_max]}" if data[:puma][:threads_min]
          lines << "- Workers: #{data[:puma][:workers]}" if data[:puma][:workers]
        end
        lines << "- Deployment: #{data[:deployment]}" if data[:deployment]
        if data[:docker]
          lines << "- Docker: #{data[:docker][:multi_stage] ? 'multi-stage' : 'single-stage'} build"
        end
        lines.join("\n") if lines.size > 1
      end

      def action_mailbox_section
        data = context[:action_mailbox]
        return if data[:error]
        return unless data[:mailboxes]&.any?

        lines = [ "## Action Mailbox" ]
        data[:mailboxes].each { |m| lines << "- `#{m[:name]}`" }
        lines.join("\n")
      end

      def migrations_section
        data = context[:migrations]
        return if data[:error]

        lines = [ "## Migrations" ]
        lines << "- Total: #{data[:total]}"
        lines << "- Schema version: #{data[:schema_version]}" if data[:schema_version]

        if data[:pending]&.any?
          lines << "### Pending Migrations (#{data[:pending].size})"
          data[:pending].each { |m| lines << "- `#{m[:version]}` #{m[:name]}" }
        end

        if data[:recent]&.any?
          lines << "### Recent Migrations"
          data[:recent].each do |m|
            actions = m[:actions]&.any? ? " (#{m[:actions].join(', ')})" : ""
            lines << "- `#{m[:version]}` #{m[:name]}#{actions}"
          end
        end

        lines.join("\n")
      end

      def seeds_section
        data = context[:seeds]
        return if data[:error]

        lines = [ "## Database Seeds" ]
        if data[:seeds_file]
          lines << "- Seeds file: #{data[:seeds_file][:exists] ? 'exists' : 'missing'}"
          lines << "- Uses Faker: yes" if data[:seeds_file][:uses_faker]
          lines << "- Environment-conditional: yes" if data[:seeds_file][:environment_conditional]
        end
        lines << "- Models seeded: #{data[:models_seeded].join(', ')}" if data[:models_seeded]&.any?

        if data[:seed_files]&.any?
          lines << "### Seed Files"
          data[:seed_files].each { |f| lines << "- `#{f[:file]}`" }
        end

        lines.join("\n")
      end

      def middleware_section
        data = context[:middleware]
        return if data[:error]

        lines = [ "## Custom Middleware" ]
        if data[:custom_middleware]&.any?
          data[:custom_middleware].each do |m|
            detail = "- `#{m[:class_name]}` (#{m[:file]})"
            detail += " — #{m[:detected_patterns].join(', ')}" if m[:detected_patterns]&.any?
            lines << detail
          end
        else
          lines << "- No custom middleware in app/middleware/"
        end

        lines.join("\n")
      end

      def engines_section
        data = context[:engines]
        return if data[:error]

        lines = [ "## Mounted Engines" ]
        if data[:mounted_engines]&.any?
          data[:mounted_engines].each do |e|
            desc = e[:description] ? " — #{e[:description]}" : ""
            lines << "- `#{e[:engine]}` at `#{e[:path]}`#{desc}"
          end
        else
          lines << "- No mounted engines"
        end

        lines.join("\n")
      end

      def multi_database_section
        data = context[:multi_database]
        return if data[:error]
        return unless data[:multi_db]

        lines = [ "## Multi-Database" ]
        if data[:databases]&.any?
          data[:databases].each do |db|
            replica = db[:replica] ? " (replica)" : ""
            lines << "- `#{db[:name]}` — #{db[:adapter]}#{replica}"
          end
        end

        if data[:model_connections]&.any?
          lines << "### Model Connections"
          data[:model_connections].each do |c|
            lines << "- `#{c[:model]}` → #{c[:connects_to] || 'custom connection'}"
          end
        end

        lines.join("\n")
      end

      def footer
        <<~MD
          ---
          _This context file is auto-generated. Run `rails ai:context` to regenerate._
        MD
      end
    end
  end
end
