# frozen_string_literal: true

module RailsAiContext
  module Serializers
    # Generates per-directory AGENTS.md files for OpenCode's lazy-loading system.
    # When OpenCode's agent reads a file, it walks up the directory tree and
    # auto-loads any AGENTS.md it finds — acting as contextual split rules.
    #
    # Generated files:
    #   app/models/AGENTS.md      — model listing, loaded when editing models
    #   app/controllers/AGENTS.md — controller listing, loaded when editing controllers
    class OpencodeRulesSerializer
      attr_reader :context

      def initialize(context)
        @context = context
      end

      # @param output_dir [String] Rails root path
      # @return [Hash] { written: [paths], skipped: [paths] }
      def call(output_dir)
        written = []
        skipped = []

        files = {
          File.join("app", "models", "AGENTS.md") => render_models_reference,
          File.join("app", "controllers", "AGENTS.md") => render_controllers_reference
        }

        files.each do |relative_path, content|
          next unless content

          filepath = File.join(output_dir, relative_path)
          dir = File.dirname(filepath)
          next unless Dir.exist?(dir)

          if File.exist?(filepath) && File.read(filepath) == content
            skipped << filepath
          else
            File.write(filepath, content)
            written << filepath
          end
        end

        { written: written, skipped: skipped }
      end

      private

      def render_models_reference
        models = context[:models]
        return nil unless models.is_a?(Hash) && !models[:error] && models.any?

        lines = [
          "# ActiveRecord Models (#{models.size})",
          "",
          "> Auto-generated by rails-ai-context. Do not edit manually.",
          "> Check here first for scopes, constants, associations. Read model files for business logic/methods.",
          ""
        ]

        models.keys.sort.first(30).each do |name|
          data = models[name]
          assocs = (data[:associations] || []).map { |a| "#{a[:type]} :#{a[:name]}" }.join(", ")
          vals = (data[:validations] || []).size
          line = "- **#{name}**"
          line += " (table: #{data[:table_name]})" if data[:table_name]
          line += " — #{assocs}" unless assocs.empty?
          line += " [#{vals}v]" if vals > 0
          lines << line
          scopes = (data[:scopes] || [])
          constants = (data[:constants] || [])
          if scopes.any? || constants.any?
            extras = []
            extras << "scopes: #{scopes.join(', ')}" if scopes.any?
            constants.each { |c| extras << "#{c[:name]}: #{c[:values].join(', ')}" }
            lines << "  #{extras.join(' | ')}"
          end
        end

        lines << "- _...#{models.size - 30} more_" if models.size > 30
        lines << ""
        lines << "Use `rails_get_model_details(model:\"Name\")` for associations, validations, scopes, enums."
        lines << "Use `rails_get_view(controller:\"name\")` for view templates."
        lines << "Use `rails_get_test_info(model:\"Name\")` for existing model tests."

        lines.join("\n")
      end

      def render_controllers_reference
        data = context[:controllers]
        return nil unless data.is_a?(Hash) && !data[:error]
        controllers = data[:controllers] || {}
        return nil if controllers.empty?

        # Filter out framework-internal controllers
        framework = %w[DeviseController Devise::OmniauthCallbacksController]
        app_controllers = controllers.reject { |name, _| framework.include?(name) }

        lines = [
          "# Controllers (#{app_controllers.size})",
          "",
          "> Auto-generated by rails-ai-context. Do not edit manually.",
          "> Read controller files directly when editing. Use MCP tools for reference only.",
          ""
        ]

        # ApplicationController before_actions
        begin
          root = defined?(Rails) ? Rails.root.to_s : Dir.pwd
          app_ctrl = File.join(root, "app", "controllers", "application_controller.rb")
          if File.exist?(app_ctrl)
            source = File.read(app_ctrl)
            before_actions = source.scan(/before_action\s+:([\w!?]+)/).flatten
            lines << "**Global before_actions:** #{before_actions.join(', ')}" << "" if before_actions.any?
          end
        rescue; end

        app_controllers.keys.sort.first(25).each do |name|
          info = app_controllers[name]
          actions = (info[:actions] || []).map { |a| a.is_a?(Hash) ? a[:name] : a }.compact
          line = "- **#{name}**"
          line += " — #{actions.join(", ")}" unless actions.empty?
          lines << line
        end

        lines << "- _...#{app_controllers.size - 25} more_" if app_controllers.size > 25

        # List service objects
        begin
          root = defined?(Rails) ? Rails.root.to_s : Dir.pwd
          services_dir = File.join(root, "app", "services")
          if Dir.exist?(services_dir)
            service_files = Dir.glob(File.join(services_dir, "*.rb"))
              .map { |f| File.basename(f, ".rb").camelize }
              .reject { |s| s == "ApplicationService" }
            lines << "" << "**Services:** #{service_files.join(', ')}" if service_files.any?
          end
        rescue; end

        # List jobs
        begin
          root = defined?(Rails) ? Rails.root.to_s : Dir.pwd
          jobs_dir = File.join(root, "app", "jobs")
          if Dir.exist?(jobs_dir)
            job_files = Dir.glob(File.join(jobs_dir, "*.rb"))
              .map { |f| File.basename(f, ".rb").camelize }
              .reject { |j| j == "ApplicationJob" }
            lines << "**Jobs:** #{job_files.join(', ')}" if job_files.any?
          end
        rescue; end

        lines << ""
        lines << "Use `rails_get_controllers(controller:\"Name\", action:\"index\")` for one action's source code."
        lines << "Use `rails_get_edit_context(file:\"path\", near:\"keyword\")` for surgical edit context."
        lines << "Use `rails_get_view(controller:\"name\")` for view templates."
        lines << "Use `rails_get_test_info(controller:\"Name\")` for existing controller tests."
        lines << "Use `rails_validate(files:[...])` to check syntax after editing — do NOT re-read files to verify."

        lines.join("\n")
      end
    end
  end
end
